// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj8BvP9fbpHe82STphSUZqF1ZY1TirRXY',
    appId: '1:546222121181:web:ad08daf01e4e9df8a2fb34',
    messagingSenderId: '546222121181',
    projectId: 'bel-sekolah-2',
    authDomain: 'bel-sekolah-2.firebaseapp.com',
    databaseURL: 'https://bel-sekolah-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bel-sekolah-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGIKF_OqzNK1kuvBG7U1M-oPlwipWpMJ8',
    appId: '1:546222121181:android:c0e1e32661f272d2a2fb34',
    messagingSenderId: '546222121181',
    projectId: 'bel-sekolah-2',
    databaseURL: 'https://bel-sekolah-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bel-sekolah-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9emMImQKDMmbSRiIO-cRO081HWZ0BAL4',
    appId: '1:546222121181:ios:820acad8b317f30aa2fb34',
    messagingSenderId: '546222121181',
    projectId: 'bel-sekolah-2',
    databaseURL: 'https://bel-sekolah-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bel-sekolah-2.appspot.com',
    iosBundleId: 'com.ta.belSekolah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9emMImQKDMmbSRiIO-cRO081HWZ0BAL4',
    appId: '1:546222121181:ios:820acad8b317f30aa2fb34',
    messagingSenderId: '546222121181',
    projectId: 'bel-sekolah-2',
    databaseURL: 'https://bel-sekolah-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bel-sekolah-2.appspot.com',
    iosBundleId: 'com.ta.belSekolah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj8BvP9fbpHe82STphSUZqF1ZY1TirRXY',
    appId: '1:546222121181:web:2d424b53b517aa98a2fb34',
    messagingSenderId: '546222121181',
    projectId: 'bel-sekolah-2',
    authDomain: 'bel-sekolah-2.firebaseapp.com',
    databaseURL: 'https://bel-sekolah-2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bel-sekolah-2.appspot.com',
  );

}